---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-app-repo
  namespace: assemble-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/backstage-2w7cf/quarkus-petclinic-gitops